config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :incident_outcomes
  resources :incidents
  devise_for :mods
  root to: 'championships#index'

  resources :championships do
    member do
      post :deregister_driver
      get  :register_driver
      post :register_driver
    end
  end
  resources :drivers do
    collection do
      get  :numbers
    end
  end
  resources :mods, only: %i[ destroy index ] do
    member do
      post :approve
    end
  end
  resources :points_allocations
  resources :points_systems
  resources :race_results do
    collection do
      get  :record
      post :record
      post :delete_all
    end
  end
  resources :races do
    member do
      post :publish_incident_outcomes
    end
  end
  resources :seasons do
    member do
      post :recalculate_all
      get  :projection
    end
  end
  resources :tracks
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :races
  has_many :results, through: :races
  has_many :scores, through: :results
  has_many :drivers, through: :races
  has_many :standings, class_name: 'SeasonStanding', inverse_of: :season
  has_many :teams
  has_many :team_standings, through: :teams
  belongs_to :championship
  belongs_to :points_system

  default_scope { order :index }

  validates :index, presence: true, uniqueness: { scope: :championship }
  validates :name, presence: true, uniqueness: { scope: :championship }

  validate :points_system_allocations_can_accommodate_results

  def calculate_scores!
    results.each do |result|
      score = result.scores.find_by points_system: points_system
      if score
        score.calculate!
        score.save
      else result.calculate_and_persist_score!
      end
    end
  end

  def calculate_standings!
    calculate_driver_standings!
    if teams.any?
      calculate_team_standings!
    end
  end

  def calculate_driver_standings!
    standings.delete_all
    if championship.combined?
      championship.track_types.each do |track_type|
        calculate_standings_for! track_type
      end
    end
    calculate_standings_for! TrackType.any
  end

  def calculate_team_standings!
    teams.each do |team|
      team.team_standings.delete_all if team.team_standings.present?
    end
    if championship.combined?
      championship.track_types.each do |track_type|
        calculate_team_standings_for! track_type
      end
    end
    calculate_team_standings_for! TrackType.any
  end

  def calculate_projection(provisional_results)
    provisional_scores = grouped_scores(TrackType.any)
    provisional_results.each do |result|
      unless provisional_scores.key? result.driver
        provisional_scores[result.driver] = {}
      end
      driver_scores = provisional_scores[result.driver]
      driver_scores[result.race] = result.calculate_score
    end
    projection = []
    standings = calculate_standings_for(TrackType.any, provisional_scores)
    sorted_drivers = standings.keys.sort_by do |driver|
      standings[driver].first
    end
    sorted_drivers.each do |driver|
      projection << [driver.name, standings[driver].first * -1]
    end
    projection
  end

  def calculate_standings_for(track_type, grouped_scores)
    grouped_sorters = {}
    grouped_scores.each_pair do |driver, race_score_map|
      all_driver_scores = race_score_map.keys.sort_by(&:date).map{ |race| race_score_map[race] }
      best_result = all_driver_scores.compact.map(&:race_result).min_by(&:effective_position)
      best_result_score = race_score_map[best_result.race]
      included_driver_scores = drop_scores(all_driver_scores, track_type)
      dropped_scores = (all_driver_scores - included_driver_scores).compact
      base_points = all_driver_scores.compact.sum(&:points)
      dropped_points = dropped_scores.sum(&:points)
      points = base_points - dropped_points
      # Points, best result, count of best result, index of first race where best result was scored
      grouped_sorters[driver] = [
        points * -1, # flip for sorting, flip back for recording
        best_result.effective_position,
        all_driver_scores.compact.count{|score| score.race_result.effective_position == best_result.effective_position } * -1, # flip for sorting
        all_driver_scores.index(best_result_score),
        dropped_scores
      ]
    end
    grouped_sorters
  end

  def calculate_team_standings_for(track_type, grouped_driver_scores)
    grouped_sorters = {}
    teams.each do |team|
      team_scores = []
      team.drivers.each do |driver|
        team_scores += grouped_driver_scores[driver].values.compact if grouped_driver_scores.has_key?(driver)
      end
      if points_system.team_results_counted_per_race && points_system.team_results_counted_per_race < team.drivers.count
        counted_team_scores = []
        races.each do |race|
          team_race_scores = team_scores.select do |score|
            score.race_result.race == race
          end.sort_by(&:points).reverse
          counted_team_scores += team_race_scores.first(points_system.team_results_counted_per_race)
        end
        team_scores = counted_team_scores
      end
      points = team_scores.sum(&:points)
      best_and_earliest_result = team_scores.map(&:race_result).min_by{ |rr| [rr.effective_position, rr.race.date]}
      grouped_sorters[team] = [
        points * -1, # flip for sorting, flip back for recording
        best_and_earliest_result.try(:effective_position),
        team_scores.count{|s| s.race_result.effective_position == best_and_earliest_result.effective_position} * -1, # flip for sorting
        races.index(best_and_earliest_result.try(:race))
      ]
    end
    grouped_sorters
  end

  def drivers_without_teams
    championship.drivers - drivers.joins(team_memberships: :team).where(teams: { season: self })
  end

  def finish_date
    races.last.date + 1.day
  end

  def grouped_results(track_type = TrackType.any)
    groups = results.of_type(track_type).group_by(&:driver)
    grouped = {}
    groups.each_pair do |driver, driver_results|
      indexed_results = {}
      driver_results.each do |result|
        indexed_results[result.race] = result
      end
      grouped[driver] = indexed_results
    end
    grouped
  end

  def grouped_scores(track_type = TrackType.any)
    groups = scores.joins(race_result: { race: :track })
      .includes(race_result: [:race, :driver])
      .where(points_system: points_system, tracks: { track_type: track_type })
      .group_by{|score| score.race_result.driver }
    grouped = {}
    groups.each_pair do |driver, driver_scores|
      indexed_scores = {}
      races.each do |race|
        next unless race.of_type? track_type
        indexed_scores[race] = driver_scores.find do |score|
          score.race_result.race == race
        end
      end
      grouped[driver] = indexed_scores
    end
    grouped
  end

  def grouped_standings(track_type = nil)
    grouped = {}
    standings.includes(:dropped_races)
      .where(track_type: SeasonStanding.effective_track_type(track_type))
      .each do |standing|
      grouped[standing.driver] = standing
    end
    grouped
  end

  def grouped_team_standings(track_type = nil)
    grouped = {}
    teams.each do |team|
      standing = team.team_standings.find_by(track_type: SeasonStanding.effective_track_type(track_type))
      grouped[team] = standing if standing.present?
    end
    grouped
  end

  def grouped_points_progression(track_type = TrackType.any)
    grouped = {}
    track_type_races = races.select do |race|
      race.of_type?(track_type)
    end
    grouped_scores.each_pair do |driver, indexed_scores|
      scores_so_far = {}
      track_type_races.each do |race|
        scores_so_far[race] = nil
      end
      points_progression = []
      track_type_races.each do |race|
        scores_so_far[race] = indexed_scores[race]
        included_scores = drop_scores(scores_so_far.values, track_type)
        if race.results.any?
          points_progression << included_scores.compact.sum(&:points)
        end
      end
      grouped[driver.name] = points_progression
    end
    grouped
  end

  def next_team_name
    "Team #{teams.count.succ}"
  end

  def ongoing?
    races.any? do |race|
      race.results.none?
    end
  end

  def scores_to_drop(track_type)
    if track_type == TrackType.any
      points_system.worst_rounds_dropped
    else
      points_system.worst_rounds_dropped / championship.track_types.count
    end
  end

  private

  def calculate_standings_for!(track_type)
    grouped_sorters = calculate_standings_for(track_type, grouped_scores(track_type))
    sorted_drivers = grouped_sorters.keys.sort_by do |driver|
      grouped_sorters[driver]
    end
    sorted_drivers.each.with_index(1) do |driver, position|
      points, _best_result_position, _count_of_best_result, _index_of_best_result, dropped_scores = grouped_sorters[driver]
      standing = standings.create! driver: driver, position: position, points: points * -1, 
        track_type: SeasonStanding.effective_track_type(track_type)
      dropped_scores.each do |score|
        standing.dropped_races.create! race_result: score.race_result
      end
    end
  end

  def calculate_team_standings_for!(track_type)
    grouped_sorters = calculate_team_standings_for(track_type, grouped_scores(track_type))
    sorted_teams = grouped_sorters.keys.sort_by do |team|
      grouped_sorters[team]
    end
    sorted_teams.each.with_index(1) do |team, position|
      points, _best_result_position, _count_of_best_result, _index_of_best_result = grouped_sorters[team]
      team.team_standings.create! position: position, points: points * -1,
        track_type: SeasonStanding.effective_track_type(track_type)
    end
  end

  def drop_scores(scores, track_type)
    scores = scores.clone
    drop_count = scores_to_drop(track_type)
    drop_count = 0 if scores.count < drop_count
    drop_count.times do 
      if scores.include? nil
        scores.delete_at scores.index(nil)
      else
        drop_score = scores.min_by(&:points)
        scores.delete drop_score
      end
    end
    scores
  end

  def points_system_allocations_can_accommodate_results
    max_allocation = points_system.points_allocations.pluck(:position).max
    return if max_allocation.nil?
    max_result = results.pluck(:position).max
    return if max_result.nil?
    if max_result > max_allocation
      errors.add :points_system, "cannot be used for this season, " +
        "as it is only configured to allocate points as far as position #{max_allocation}. " +
        "This season currently requires a points system to allocate points as far as position #{max_result}."
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_championship, only: %i[index new]
  before_action :set_season, only: %i[ edit update destroy projection recalculate_all ]
  before_action :authenticate_mod!, except: %i[ index projection ]

  # GET /seasons or /seasons.json
  def index
    @seasons = @championship.seasons
    construct_championship_statistics
    @incident_drivers = @championship.drivers_with_active_published_incident_outcomes
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
    @championship = @season.championship
  end

  # POST /seasons or /seasons.json
  def create
    @season = Season.new(season_params)
    @championship = @season.championship

    respond_to do |format|
      if @season.save
        format.html { redirect_to races_path(season: @season), notice: "Season was successfully created." }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1 or /seasons/1.json
  def update
    respond_to do |format|
      recalculate_needed = @season.points_system_id_changed?
      if @season.update(season_params)
        @season.calculate_scores!
        @season.races.each(&:award_most_laps_led!)
        @season.calculate_standings!
        format.html { redirect_to races_path(season: @season), notice: "Season was successfully updated." }
        format.json { render :show, status: :ok, location: @season }
      else
        @championship = @season.championship
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1 or /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: "Season was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def projection
    respond_to do |format|
      format.html do
        if params[:drivers].present?
          @drivers = Driver.find(params.require(:drivers))
          @standings = @season.standings.where track_type: nil
        else
          if params[:selected]
            @selected = Driver.find(params.require(:selected))
          else
            @selected = Driver.none
          end
          @all_drivers = Driver.all
        end
        render :projection
      end
      format.json do
        race = @season.races.select(&:incomplete?).sort_by(&:date).first
        head :bad_request unless race
        render json: @season.calculate_projection(construct_provisional_results(race))
      end
    end
  end

  def recalculate_all
    @season.calculate_scores!
    @season.races.each(&:award_most_laps_led!)
    @season.calculate_standings!
    redirect_to races_path(season: @season, track_type: params[:track_type])
  end

  private

    def construct_championship_statistics
      @statistics = {}
      if @championship.combined?
        @statistics['combined'] = construct_discipline_statistics(TrackType.any)
      end
      @championship.track_types.each do |track_type|
        @statistics[track_type] = construct_discipline_statistics(track_type)
      end
    end

    def construct_discipline_statistics(discipline)
      {
        count: @championship.races_completed(track_type: discipline),
        lap_count: @championship.laps_completed(track_type: discipline),
        wins: @championship.wins(track_type: discipline)
          .group_by(&:driver)
          .map{ |driver, wins| [driver, wins.count]}
          .sort_by(&:last)
          .reverse,
        pole_positions: @championship.pole_positions(track_type: discipline)
          .group_by(&:driver)
          .map{ |driver, poles| [driver, poles.count]}
          .sort_by(&:last)
          .reverse,
        most_laps_led: @championship.results_with_most_laps_led(track_type: discipline)
          .group_by(&:driver)
          .map{ |driver, mll| [driver, mll.count] }
          .sort_by(&:last)
          .reverse,
        laps_led: @championship.results_with_any_laps_led(track_type: discipline)
          .group_by(&:driver)
          .map{ |driver, results| [driver, results.sum(&:laps_led)] }
          .sort_by(&:last)
          .reverse
          .first(10),
        average_finishing_position: @championship.finishes(track_type: discipline)
          .group_by(&:driver)
          .select{|driver, finishes| finishes.count >= 5 }
          .map{|driver, finishes| [driver, finishes.sum(&:position) / finishes.count.to_f]}
          .sort_by(&:last)
          .first(10)
      }
    end

    def construct_provisional_results(race)
      results = []
      # can't require since might be empty
      pole_position_driver = Driver.find_by id: params[:polePosition]
      most_laps_led_driver = Driver.find_by id: params[:ledMostLaps]
      params.require(:drivers).each do |_index, driver_data|
        result = RaceResult.new
        result.race = race
        result.driver = Driver.find_by id: driver_data.require(:driverID)
        result.scored_pole_position = result.driver == pole_position_driver
        result.most_laps_led = result.driver == most_laps_led_driver
        result.laps_led = driver_data.require(:ledLap) == 'true' ? 1 : 0
        result.finished_race = driver_data.require(:dnf) == 'false'
        result.position = driver_data.require(:position).to_i
        results << result
      end
      results
    end

    def set_championship
      @championship = Championship.find params.require(:championship)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def season_params
      params.require(:season).permit(:championship_id, :points_system_id, :index, :name)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.haml
= form_with(model: season) do |form|
  - if season.errors.any?
    #error_explanation
      %h2
        = pluralize(season.errors.count, "error")
        prohibited this season from being saved:
      %ul
        - season.errors.each do |error|
          %li= error.full_message
  = form.hidden_field :championship_id, value: @championship.id
  .field
    = form.label :index
    = form.number_field :index, value: season.persisted? ? season.index : @championship.next_season_index
  .field
    = form.label :points_system
    = form.select :points_system_id, options_from_collection_for_select(PointsSystem.all, :id, :name, season.points_system_id)
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/seasons/_race_results_table.haml
%h2 Drivers
%table.race-results
  %thead
    %tr
      %th.empty
      %th Driver
      - @races.each do |race|
        %th.race{colspan: 2, class: ('warning' if race.warnings.any?)}
          .race-date= link_to race.date, race
          .race-track-name
            .track-name
              = link_to race.track.name, race_results_path(race: race)
              - if mod_signed_in? && race.results.none?
                .record-results= link_to '(record results)', race_results_path(race: race)
      - if @season.points_system.drops_rounds?
        %th 
          Base
          %br
          points
        %th
          Dropped
          %br
          points
      %th Total points
  %tbody
    - @drivers.each do |driver|
      %tr
        - standing = @standings[driver]
        %td= standing.position
        %td.driver-name{class: ('championship-contender' if driver.in_championship_contention?(season: @season))}= link_to driver.championship_name(@season.championship), driver
        - @races.each do |race|
          - result = @results[driver][race]
          - if result
            %td.result{class: race_result_classes(result)}
              = result.effective_position_text
            - score = @scores[driver][race]
            %td.score{class: ('dropped' if standing.drops? result)}= link_to score.points, result
          - else
            %td
            %td
        - if @season.points_system.drops_rounds?
          %td= standing.base_points
          %td= standing.dropped_points
        %td.points= standing.points
- if @teams.any?
  %h2 Teams
  %table.race-results
    %thead
      %tr
        %th.empty
        %th Team
        %th Driver
        - @races.each do |race|
          %th.race{colspan: 2}
            .race-date= race.date
            .race-track-name
              .track-name= race.track.name
    %tbody
      - @teams.each do |team|
        - team.drivers.sort_by{ |driver| @drivers.index(driver) || @drivers.count }.each.with_index do |driver, driver_index|
          %tr
            - standing = @team_standings[team]
            - if driver_index == 0
              %td{rowspan: team.drivers.count}= standing.position
              %td.driver-name{rowspan: team.drivers.count}= team.name
            %td.driver-name= driver.name
            - @races.each do |race|
              - result = @results[driver].try(:[], race)
              - if result
                %td.result{class: race_result_classes(result)}= result.effective_position_text
                - score = @scores[driver][race]
                %td.score{class: ('dropped' unless result.counts_for_team?(team))}= score.points
              - else
                %td
                %td
            - if driver_index == 0
              %td.points{rowspan: team.drivers.count}= standing.points

app/views/seasons/edit.html.haml
%h1 Editing Season
= render 'form', season: @season
= link_to 'Show', @season
|
= link_to 'Back', seasons_path

app/views/seasons/index.html.haml
- title @championship.name
%p#notice= notice
%h1 #{@championship.name} Seasons
%table
  %thead
    %tr
      %th Name
      %th Points system
      - if mod_signed_in?
        %th{:colspan => "2"}
  %tbody
    - @seasons.each do |season|
      %tr
        %td= link_to season.name, races_path(season: season)
        %td= link_to season.points_system.name, season.points_system
        - if mod_signed_in?
          %td= link_to 'Edit', edit_season_path(season)
          %td= link_to 'Teams', teams_path(season: season)
          %td= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' }
%h2 Championship Statistics
- @statistics.each_pair do |track_type, statistics|
  %h3
    = track_type.capitalize
    (#{statistics[:count]} races, #{statistics[:lap_count]} laps)
  %span.statistics
    .stat
      Wins
      = render 'championships/driver_stat_table', statistic: statistics[:wins]
    .stat
      Pole positions
      = render 'championships/driver_stat_table', statistic: statistics[:pole_positions]
    .stat
      Races with most laps led
      = render 'championships/driver_stat_table', statistic: statistics[:most_laps_led]
    .stat
      Top 10: Laps led
      = render 'championships/driver_stat_table', statistic: statistics[:laps_led]
    .stat
      Top 10: Average finishing position (at least 5 races finished)
      = render 'championships/driver_stat_table', statistic: statistics[:average_finishing_position]  
- if @incident_drivers.any?
  %h2 Drivers with Active Incident Outcomes
  %table
    %thead 
      %tr
        %th Driver
        %th Active warnings
        %th Active penalty points
    %tbody
      - @incident_drivers.each do |driver|
        %tr
          %td= link_to driver.name, driver
          %td= driver.current_warnings(@championship)
          %td= driver.current_penalty_points(@championship)
%br/
- if mod_signed_in?
  = link_to 'New Season', new_season_path(championship: @championship)

app/views/seasons/new.html.haml
%h1 New Season
= render 'form', season: @season
= link_to 'Back', seasons_path

app/views/seasons/projection.haml
- title 'Points Projection'
%h1= @season.name
%h2 Points Standings Live Projection
= link_to "Back to #{@season.name}", races_path(season: @season)

- if @drivers.present?
  Drag drivers to reorder and preview points standings projections.
  .projection
    .positions
      %ul
        - 1.upto(@drivers.count).each do |n|
          %li.position-number= n
    .driver-positions
      %ul.drivers
        - @drivers.each do |driver|
          %li.driver{ data: { driver_id: driver.id } }
            .driver-name= driver.name
            .led-lap
              .text Led a lap
              %span.icon &#10004;
            .dnf
              .text DNF
              %span.icon &#10006;
    .points
      %table
        %tr
          %td= label_tag :pole_position, 'Pole position:'
          %td= select_tag :pole_position, options_from_collection_for_select(@drivers, :id, :name), include_blank: true
        %tr
          %td= label_tag :led_most_laps, 'Led most laps:'
          %td= select_tag :led_most_laps, options_from_collection_for_select(@drivers, :id, :name), include_blank: true
      .projection-results
        %table
          %thead 
            %tr
              %th Standings before race
              %th Provisional standings after race
          %tbody
            %tr
              %td
                %table
                  - @standings.each do |standing|
                    %tr
                      %td= standing.position
                      %td= standing.driver.name
                      %td= standing.points
              %td
                .results
  = link_to 'Reselect drivers', projection_season_path(@season, selected: @drivers.pluck(:id))
- else
  .selection
    Select drivers who are entered in the race:
    = form_with url: projection_season_path(@season), method: :get do |form|
      - drivers_per_column = 20
      - columns = (@all_drivers.count / drivers_per_column) + 1
      %table
        - 1.upto(drivers_per_column).each do |row|
          %tr
            - 1.upto(columns).each do |column|
              - driver_index = (column - 1) * drivers_per_column + row - 1
              - driver = @all_drivers[driver_index]
              - if driver
                %td= form.check_box :drivers, { multiple: true, checked: @selected.include?(driver)}, driver.id, nil
                %td= form.label "drivers_#{driver.id}", driver.name
      = form.submit 'Select drivers'

app/views/seasons/show.html.haml
%p#notice= notice
%p
  %strong Championship:
  = @season.championship_id
%p
  %strong Points system:
  = @season.points_system_id
%p
  %strong Index:
  = @season.index
%p
  %strong Name:
  = @season.name
= link_to 'Edit', edit_season_path(@season)
|
= link_to 'Back', seasons_path