config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :incident_outcomes
  resources :incidents
  devise_for :mods
  root to: 'championships#index'

  resources :championships do
    member do
      post :deregister_driver
      get  :register_driver
      post :register_driver
    end
  end
  resources :drivers do
    collection do
      get  :numbers
    end
  end
  resources :mods, only: %i[ destroy index ] do
    member do
      post :approve
    end
  end
  resources :points_allocations
  resources :points_systems
  resources :race_results do
    collection do
      get  :record
      post :record
      post :delete_all
    end
  end
  resources :races do
    member do
      post :publish_incident_outcomes
    end
  end
  resources :seasons do
    member do
      post :recalculate_all
      get  :projection
    end
  end
  resources :tracks
end

app/models/championship.rb
class Championship < ApplicationRecord
  has_many :seasons
  has_many :races, through: :seasons
  has_many :incidents, through: :races
  has_many :outcomes, through: :incidents
  has_many :tracks, through: :races
  has_many :results, through: :seasons
  has_many :championship_drivers
  has_many :drivers, through: :championship_drivers

  default_scope { order :name }

  validates :name, presence: true, uniqueness: true
  validates :number_of_warnings_per_penalty_point, presence: true, if: :warnings_convert_to_penalty_points?

  def combined?
    track_types.count > 1
  end

  def drivers_with_active_published_incident_outcomes
    Driver.find(outcomes.active.published.pluck(:driver_id))
  end

  def finishes(track_type:)
    results.joins(race: :track).where(tracks: { track_type: track_type }).not_disqualified
  end

  def free_numbers_below_100
    0.upto(99).to_a - championship_drivers.pluck(:car_number).compact.map(&:to_i) - [1] # champs
  end

  def laps_completed(track_type:)
    races.joins(:track, :results).where(tracks: { track_type: track_type }).uniq.sum(&:laps)
  end

  def next_season_index
    if seasons.any?(&:persisted?)
      seasons.select(&:persisted?).map(&:index).max.succ
    else 1
    end
  end

  def pole_positions(track_type:)
    finishes(track_type: track_type).where(scored_pole_position: true)
  end

  def races_completed(track_type:)
    races.joins(:track, :results).where(tracks: { track_type: track_type }).uniq.count
  end

  def results_with_any_laps_led(track_type:)
    finishes(track_type: track_type).where('laps_led > 0')
  end

  def results_with_most_laps_led(track_type:)
    results_with_any_laps_led(track_type: track_type)
      .group_by(&:race).values.map do |race_results|
        most_laps_led = race_results.map(&:laps_led).max
        race_results.select do |race_result|
          race_result.laps_led == most_laps_led
        end
      end.flatten
  end

  def track_types
    tracks.pluck(:track_type).uniq
  end

  # TODO this doesn't account for the winner being disqualified
  def wins(track_type:)
    finishes(track_type: track_type).where(position: 1)
  end
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_action :set_championship, only: %i[ deregister_driver show edit register_driver update destroy ]
  before_action :authenticate_mod!, except: %i[ index show ]

  # GET /championships or /championships.json
  def index
    @championships = Championship.all
  end

  # GET /championships/1 or /championships/1.json
  def show
  end

  # GET /championships/new
  def new
    @championship = Championship.new
  end

  # GET /championships/1/edit
  def edit
  end

  # POST /championships or /championships.json
  def create
    @championship = Championship.new(championship_params)

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: "Championship was successfully created." }
        format.json { render :show, status: :created, location: @championship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /championships/1 or /championships/1.json
  def update
    respond_to do |format|
      if @championship.update(championship_params)
        format.html { redirect_to @championship, notice: "Championship was successfully updated." }
        format.json { render :show, status: :ok, location: @championship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1 or /championships/1.json
  def destroy
    @championship.destroy
    respond_to do |format|
      format.html { redirect_to championships_url, notice: "Championship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def deregister_driver
    @driver = Driver.find(params.require(:driver_id))
    @driver.championship_entry(@championship).destroy
    redirect_to drivers_url(championship: @championship), notice: 'Driver was successfully deregistered from championship.'
  end

  def register_driver
    if request.get?
      @drivers = Driver.all - @championship.drivers
    else
      @driver = Driver.find(params.require(:driver_id))
      @entry = ChampionshipDriver.new(championship: @championship, driver: @driver, car_number: params.require(:car_number))
      if @entry.save
        redirect_to drivers_url(championship: @championship), notice: 'Driver registered to championship.'
      else
        redirect_to register_driver_championship_url(@championship), notice: "Car number #{@entry.car_number} is already assigned in this championship."
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_championship
      @championship = Championship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def championship_params
      params.require(:championship).permit(:name, :warnings_convert_to_penalty_points, :number_of_warnings_per_penalty_point)
    end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_driver_stat_table.haml
%table
  %tbody
    - statistic.each do |(driver, count)|
      %tr
        %td= link_to driver.name, driver
        %td
          - if count.is_a? Integer
            = count
          - else
            = count.round(2)

app/views/championships/_form.html.haml
= form_with(model: championship) do |form|
  - if championship.errors.any?
    #error_explanation
      %h2
        = pluralize(championship.errors.count, "error")
        prohibited this championship from being saved:
      %ul
        - championship.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :warnings_convert_to_penalty_points?
    = form.check_box :warnings_convert_to_penalty_points
  .field
    = form.label :number_of_warnings_per_penalty_point
    = form.number_field :number_of_warnings_per_penalty_point, min: 2
  .actions
    = form.submit

app/views/championships/edit.html.haml
- title "Editing #{@championship.name}"
%h1 Editing Championship
= render 'form', championship: @championship
= link_to 'Show', @championship
|
= link_to 'Back', championships_path

app/views/championships/index.html.haml
- title 'Championships'
%p#notice= notice
%h1 Championships
%table
  %thead
    %tr
      %th Name
      %th{colspan: 3}
  %tbody
    - @championships.each do |championship|
      %tr
        %td= link_to championship.name, seasons_path(championship: championship)
        %td= link_to 'Edit', edit_championship_path(championship)
        %td= link_to 'Drivers', drivers_path(championship: championship)
        %td= link_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' }
- if mod_signed_in?
  %br/
  = link_to 'New Championship', new_championship_path

app/views/championships/new.html.haml
- title 'New Championship'
%h1 New Championship
= render 'form', championship: @championship
= link_to 'Back', championships_path

app/views/championships/register_driver.haml
- title 'Register Driver'
%p#notice= notice
%h1 Register Driver

= form_with url: register_driver_championship_url(@championship) do |form|
  .field
    = form.label :driver_id, 'Driver'
    = form.select :driver_id, options_from_collection_for_select(@drivers, :id, :name)
  .field
    = form.label :car_number
    = form.text_field :car_number
  .actions
    = form.submit 'Register driver to championship'

app/views/championships/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @championship.name
%p
  %strong Warnings convert to penalty points?
  = @championship.warnings_convert_to_penalty_points? ? 'Yes' : 'No'
%p
  %strong Number of warnings per penalty point:
  = @championship.number_of_warnings_per_penalty_point

.links
  =link_to 'Seasons', seasons_path(championship: @championship)
= link_to 'Edit', edit_championship_path(@championship)
|
= link_to 'Back', championships_path