config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :incident_outcomes
  resources :incidents
  devise_for :mods
  root to: 'championships#index'

  resources :championships do
    member do
      post :deregister_driver
      get  :register_driver
      post :register_driver
    end
  end
  resources :drivers do
    collection do
      get  :numbers
    end
  end
  resources :mods, only: %i[ destroy index ] do
    member do
      post :approve
    end
  end
  resources :points_allocations
  resources :points_systems
  resources :race_results do
    collection do
      get  :record
      post :record
      post :delete_all
    end
  end
  resources :races do
    member do
      post :publish_incident_outcomes
    end
  end
  resources :seasons do
    member do
      post :recalculate_all
      get  :projection
    end
  end
  resources :tracks
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :season
  belongs_to :track
  has_many :results, class_name: 'RaceResult', inverse_of: :race
  has_many :drivers, through: :results
  has_many :incidents
  has_many :outcomes, through: :incidents

  default_scope { order :date }

  scope :in_championship, -> (championship) { joins(:season).where(seasons: { championship: championship } ) }
  scope :of_type, -> (track_type) { joins(:track).where(tracks: { track_type: track_type }) }

  validates :date, presence: true, uniqueness: { scope: :season }
  validates :laps, presence: true

  def award_most_laps_led!
    most_laps_led = results.pluck(:laps_led).max
    results.where(laps_led: most_laps_led).update_all(most_laps_led: true)
    results.where('laps_led < ?', most_laps_led).update_all(most_laps_led: false)
    results.each do |result|
      result.scores.each do |score|
        score.calculate!
        score.save!
      end
    end
  end

  def incomplete?
    results.none?
  end

  def name
    "#{track.name} (#{season.name})"
  end

  def of_type?(track_type)
    if track_type == TrackType.any
      true
    else track.track_type == track_type
    end
  end

  def publish_incident_outcomes!
    outcomes.update_all published: true
  end

  def unpublished_outcomes
    outcomes.unpublished
  end

  def warnings
    return [] if results.none?
    messages = []
    poles = results.where(scored_pole_position: true)
    laps_led = results.sum(:laps_led)
    if poles.count != 1
      messages << "should have 1 driver who scored pole position, but hsa #{poles.count}"
    end
    if laps_led != laps
      messages << "should have #{laps} led, but has #{laps_led} led"
    end
    messages
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy publish_incident_outcomes ]
  before_action :set_season, only: %i[index new ]
  before_action :authenticate_mod!, except: %i[ index show ]

  # GET /races or /races.json
  def index
    if params[:track_type] && TrackType.types.include?(params[:track_type])
      @track_type = params[:track_type]
      track_type = params.require(:track_type)
    else 
      # Don't set instance variable
      track_type = TrackType.any
    end
    @races = @season.races.of_type(track_type)
    @standings = @season.grouped_standings(track_type)
    @team_standings = @season.grouped_team_standings(track_type)
    @drivers = @standings.keys.sort_by {|driver| @standings[driver].position }
    @teams = @team_standings.keys.sort_by{ |team| @team_standings[team].position }
    @results = @season.grouped_results(track_type)
    @scores = @season.grouped_scores(track_type)
    @points_progression = @season.grouped_points_progression(track_type)
  end

  # GET /races/new
  def new
    @race = Race.new
    if @season.races.any?
      @race.date = @season.races.pluck(:date).max + 1.week
    end
  end

  # GET /races/1/edit
  def edit
    @season = @race.season
  end

  # POST /races or /races.json
  def create
    @race = Race.new(race_params)
    @season = @race.season

    respond_to do |format|
      if @race.save
        format.html { redirect_to races_path(season: @season), notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish_incident_outcomes
    @race.publish_incident_outcomes!
    redirect_to race_results_path(race: @race), notice: 'Incident outcomes published.'
  end

  # PATCH/PUT /races/1 or /races/1.json
  def update
    @season = @race.season
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to races_path(season: @season), notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1 or /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    def set_season
      @season = Season.find params.require(:season)
    end

    # Only allow a list of trusted parameters through.
    def race_params
      params.require(:race).permit(:season_id, :track_id, :date, :laps)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.haml
= form_with(model: race) do |form|
  - if race.errors.any?
    #error_explanation
      %h2
        = pluralize(race.errors.count, "error")
        prohibited this race from being saved:
      %ul
        - race.errors.each do |error|
          %li= error.full_message
  = form.hidden_field :season_id, value: @season.id
  = form.hidden_field :index, value: @season.races.count.succ
  .field
    = form.label :track
    = form.select :track_id, options_from_collection_for_select(Track.all, :id, :name, race.track_id)
  .field
    = form.label :date
    = form.date_select :date
  .field
    = form.label :laps
    = form.number_field :laps
  .actions
    = form.submit

app/views/races/edit.html.haml
- title "Editing #{@race.name}"
%h1 Editing #{@race.name}
= render 'form', race: @race
= link_to 'Show', @race
|
= link_to 'Back', races_path

app/views/races/index.html.haml
- title @season.name
%p#notice= notice
%h1= @season.name
Points system:
= link_to @season.points_system.name, @season.points_system
%br
- if @season.championship.combined?
  - @season.championship.track_types.each do |track_type|
    = link_to "View #{track_type} standings", races_path(season: @season, track_type: track_type)
    %br
  - if @track_type
    = link_to "View all standings", races_path(season: @season)
- if @season.ongoing?
  %br
  = link_to 'Points standings live projection', projection_season_path(@season)
- if @season.races.any?
  = render partial: 'seasons/race_results_table'
  %h2 Points Progression (Drivers)
  Drivers who have been in the top 5 of the standings at any point are shown by default.
  %br
  Click on the driver names above the chart to show any others.
  %br
  %canvas#points_progression
- if @season.standings.any? && mod_signed_in?
  = button_to 'Recalculate standings', recalculate_all_season_path(@season, track_type: @track_type)
%br/
- if mod_signed_in?
  = link_to 'New Race', new_race_path(season: @season)
  %br
  = link_to 'Teams', teams_path(season: @season)
  %br
= link_to "Back to #{@season.championship.name}", seasons_path(championship: @season.championship)
#points_progression_labels= @races.map(&:track).map(&:name).to_json
#points_progression_data= @points_progression.to_json

app/views/races/new.html.haml
%h1 New Race
= render 'form', race: @race
= link_to 'Back', races_path

app/views/races/show.html.haml
- title @race.name
%p#notice= notice
%p
  %strong Season:
  = @race.season.name
%p
  %strong Track:
  = @race.track.name
%p
  %strong Date:
  = @race.date
%p
  %strong Laps:
  = @race.laps
- if mod_signed_in?
  = link_to 'Edit', edit_race_path(@race, season: @season)