config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :incident_outcomes
  resources :incidents
  devise_for :mods
  root to: 'championships#index'

  resources :championships do
    member do
      post :deregister_driver
      get  :register_driver
      post :register_driver
    end
  end
  resources :drivers do
    collection do
      get  :numbers
    end
  end
  resources :mods, only: %i[ destroy index ] do
    member do
      post :approve
    end
  end
  resources :points_allocations
  resources :points_systems
  resources :race_results do
    collection do
      get  :record
      post :record
      post :delete_all
    end
  end
  resources :races do
    member do
      post :publish_incident_outcomes
    end
  end
  resources :seasons do
    member do
      post :recalculate_all
      get  :projection
    end
  end
  resources :tracks
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :race_results
  has_many :races, through: :race_results
  has_many :seasons, through: :races
  has_many :championship_drivers
  has_many :championships, through: :championship_drivers
  has_many :incident_outcomes
  has_many :incidents, through: :incident_outcomes
  has_many :team_memberships
  has_many :teams, through: :team_memberships

  default_scope { order :name }

  validates :name, presence: true, uniqueness: true

  def championship_entry(championship)
    championship_drivers.find_by championship: championship
  end

  def championship_name(championship)
    championship_entry(championship).try(:numbered_name) || name
  end

  def current_championship_outcomes(championship)
    incident_outcomes.active.published.joins(incident: { race: :season })
       .where(seasons: { championship_id: championship.id })
  end

  def current_warnings(championship)
    championship_warnings = current_championship_outcomes(championship).where(received_warning: true).uniq.count
    if championship.warnings_convert_to_penalty_points?
      championship_warnings = championship_warnings % championship.number_of_warnings_per_penalty_point
    end
    return championship_warnings
  end

  def current_penalty_points(championship)
    championship_penalty_points = current_championship_outcomes(championship).pluck(:penalty_points).inject(:+) || 0
    if championship.warnings_convert_to_penalty_points?
      championship_warnings = current_championship_outcomes(championship).where(received_warning: true).uniq.count
      championship_penalty_points += championship_warnings / championship.number_of_warnings_per_penalty_point
    end
    championship_penalty_points
  end

  def in_championship_contention?(season:)
    return false unless season.ongoing?
    rounds_still_to_occur = season.races.select do |race|
      race.results.none?
    end
    score_to_beat = season.standings.pluck(:points).max
    race_scores = {}
    season.races.each do |race|
      result = race.results.find_by(driver_id: id)
      race_scores[race] = if result
                            result.scores.find_by(points_system: season.points_system).try(:points)
                          else 0
                          end
    end
    rounds_still_to_occur.each do |race|
      race_scores[race] = season.points_system.max_possible_points_per_race
    end
    scores = race_scores.values
    number_of_rounds_to_drop = 0
    unless season.points_system.worst_rounds_dropped > season.races.count
      number_of_rounds_to_drop = season.points_system.worst_rounds_dropped
    end
    number_of_rounds_to_drop.times do
      scores.delete_at scores.index(scores.min)
    end
    potential_max_score = scores.sum
    potential_max_score >= score_to_beat
  end

  def inferred_championships
    seasons.map(&:championship).uniq
  end

  def last_season_raced(championship)
    races.in_championship(championship).last.try(:season)
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_championship, only: %i[ create edit new index numbers update ]
  before_action :set_driver, only: %i[ show edit update destroy ]
  before_action :authenticate_mod!, except: %i[ index show numbers ]

  # GET /drivers or /drivers.json
  def index
    @drivers = @championship.drivers
  end

  # GET /drivers/1 or /drivers/1.json
  def show
    construct_driver_results
    @incidents = @driver.incidents
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
    @entry = ChampionshipDriver.new championship: @championship, driver: @driver
  end

  # GET /drivers/1/edit
  def edit
    @entry = @driver.championship_entry(@championship)
  end

  # POST /drivers or /drivers.json
  def create
    @driver = Driver.new(driver_params)
    @entry = ChampionshipDriver.new(championship_driver_params)
    @entry.driver = @driver

    respond_to do |format|
      if @driver.save && @entry.save
        format.html { redirect_to drivers_path(championship: @championship), notice: "Driver was successfully created and registered to championship." }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1 or /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params) && @driver.championship_entry(@championship).update(championship_driver_params)
        format.html { redirect_to drivers_path(championship: @championship), notice: "Driver was successfully updated." }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1 or /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url(championship: @championship), notice: "Driver was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def numbers
    @drivers = @championship.championship_drivers.with_car_number.sort_by(&:car_number_as_integer).map(&:driver)
    @by_season = @drivers.group_by do |driver|
      driver.last_season_raced(@championship)
    end
    @free = @championship.free_numbers_below_100
    #binding.pry
  end

  private
    def set_championship
      @championship = Championship.find params.require(:championship)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def driver_params
      params.require(:driver).permit(:name, :car_number, championship_driver: %i[car_number championship_id]).except(:championship_driver)
    end

    def championship_driver_params
      params.require(:driver).require(:championship_driver).permit(:car_number, :championship_id)
    end

    def construct_driver_results
      @results = {}
      @driver.championships.includes(seasons: [:standings, races: :results]).each do |championship|
        @results[championship] = {}
        @results[championship][:seasons] = {}
        championship.seasons.select do |season|
          season.drivers.include? @driver          
        end.each do |season|
          races = {}
          season.races.each do |race|
            races[race] = race.results.find_by(driver_id: @driver.id)
          end
          @results[championship][:seasons][season] = {
            standing: season.standings.find_by(driver_id: @driver.id,
              track_type: SeasonStanding.effective_track_type(TrackType.any)),
            races: races
          }
        end
        @results[championship][:table_width] = championship.seasons.max_by do |season|
          season.races.count
        end.races.count
      end
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.haml
= form_with(model: driver, url: driver.persisted? ? driver_path(driver, championship: @championship) : drivers_path(championship: @championship)) do |form|
  - if driver.errors.any?
    #error_explanation
      %h2
        = pluralize(driver.errors.count, "error")
        prohibited this driver from being saved:
      %ul
        - driver.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :name
    = form.text_field :name
  = form.fields_for :championship_driver, @entry do |entry_fields|
    .field
      = entry_fields.hidden_field :championship_id, value: @championship.id
      = entry_fields.label :car_number
      = entry_fields.text_field :car_number
  .actions
    = form.submit

app/views/drivers/_race_results_table.haml
- empty_cells = table_width - results[:races].keys.count
%table.race-results
  %thead
    %tr
      - results[:races].keys.each do |race|
        %th.race
          .race-date= race.date
          .race-track-name
            .track-name= race.track.name
      - empty_cells.times do |empty_cell|
        %th.race
          .race-date
          .race-track-name
      %th Points
      %th Position
      - if season.ongoing?
        %th
          Championship
          %br
          contention?
  %tbody
    %tr
      - results[:races].values.each do |race_result|
        - if race_result
          %td.result{class: race_result_classes(race_result)}= race_result.effective_position_text
        - else
          %td.result
      - empty_cells.times do |empty_cell|
        %td.result
      %td.points
        = results[:standing].points
        - if season.ongoing?
          *
      %td.result{class: standing_class(results[:standing])}
        = results[:standing].position
        - if season.ongoing?
          *
      - if season.ongoing?
        %td
          - if @driver.in_championship_contention?(season: season)
            Yes
          - else
            No
- if season.ongoing?
  *
  &mdash;
  %em Season ongoing.
  %br

app/views/drivers/edit.html.haml
- title "Editing #{@driver.name}"
%h1 Editing Driver
= render 'form', driver: @driver
= link_to 'Show', @driver
|
= link_to 'Back', drivers_path

app/views/drivers/index.html.haml
- title 'Drivers'
%p#notice= notice
%h1 Drivers
= link_to 'Numbers', numbers_drivers_path(championship: @championship)
%table
  %thead
    %tr
      %th Name
      %th Car Number
      %th Races
      %th Last season raced
      %th{:colspan => "3"}
  %tbody
    - @drivers.each do |driver|
      %tr
        %td= driver.name
        %td= driver.championship_entry(@championship).car_number
        %td= driver.races.in_championship(@championship).count
        %td
          - season = driver.last_season_raced(@championship)
          - if season.present?
            = link_to season.name, races_path(season: season)
        %td= link_to 'Show'
        %td= link_to 'Edit', edit_driver_path(driver, championship: @championship)
        %td= link_to 'Deregister', deregister_driver_championship_path(@championship, driver_id: driver.id), method: :post, data: { confirm: 'Are you sure?' }
        %td= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Driver', new_driver_path(championship: @championship)
= link_to 'Register Existing Driver', register_driver_championship_path(@championship)

app/views/drivers/new.html.haml
%h1 New Driver
= render 'form', driver: @driver
= link_to 'Back', drivers_path

app/views/drivers/numbers.haml
- title 'Driver Numbers'
%h1 Driver Numbers
%h2 Free Numbers Below 100
%table
  %tbody
    - 0.upto(9).each do |tens_digit|
      %tr
        - 0.upto(9).each do |ones_digit|
          %td
            - n = tens_digit * 10 + ones_digit
            - if @free.include? n
              = n
%h2 All Numbers
%table
  %thead
    %tr
      %th Number
      %th Driver
      %th Last Season Raced
  %tbody
    - @drivers.each do |driver|
      %tr
        %td= driver.championship_entry(@championship).car_number
        %td= link_to driver.name, driver
        %td= driver.last_season_raced(@championship).try(:name)

%h2 Numbers by Last Season Raced
- @by_season.each_pair do |season, drivers|
  %h3= season.try(:name) || 'Never Raced'
  %table
    %thead
      %tr
        %th Number
        %th Driver
    %tbody
      - drivers.each do |driver|
        %tr
          %td= driver.championship_entry(@championship).car_number
          %td= link_to driver.name, driver

app/views/drivers/show.html.haml
- title @driver.name
%p#notice= notice
%p
  %strong Name:
  = @driver.name
%h2 Championship Results
- @results.each_pair do |championship, championship_data|
  %h2= link_to championship.name, seasons_path(championship: championship)
  - seasons = championship_data[:seasons]
  - table_width = championship_data[:table_width]
  %b Currently active warnings:
  = @driver.current_warnings(championship)
  %br
  %b Currently active penalty points:
  = @driver.current_penalty_points(championship)
  - seasons.each_pair do |season, season_results|
    %h3
      = link_to season.name, races_path(season: season)
      - if season.ongoing?
        (ongoing)
    = render 'race_results_table', season: season, results: season_results, table_width: table_width
- if @incidents.any?
  %h2 Incidents
  = render 'incidents/table'